title: Roped In
subTitle: "Sernig God in Germany"
author: James and Beth Roper

disqus_shortname: ropedin

description: |
  Hi! We're James and Beth, we are a couple that helped plant a church in Berlin, Germany.
  This is our story. 
