title: all that jazz
subTitle: "james' blog about scala and all that jazz"
author: James Roper

theme: themes.Theme$

disqus_shortname: jazzyidau

description: |
  <img style="float: right; margin: 5px;" src="images/james.jpg"/>
  Hi! My name is James Roper, and I am a software developer with a particular interest in open source
  development and trying new things. I program in Scala, Java, PHP, Python and Javascript, and I work
  for <a href="https://lightbend.com">Lightbend</a> as a developer on
  <a href="http://lagomframework.com">Lagom</a>. I also have a full life outside the world of IT,
  enjoy playing a variety of musical instruments and sports, and currently I live in Canberra.
  <br/>
  <br/>
  <div class="twitter-btn-o"><a class="twitter-btn" title="Follow @jroper on Twitter" href="https://twitter.com/intent/follow?original_referer=https%3A%2F%2Fjazzy.id.au%2F&amp;ref_src=twsrc%5Etfw&amp;region=follow_link&amp;screen_name=jroper&amp;tw_p=followbutton" target="_blank" onclick="window.open(event.currentTarget.getAttribute('href'),'twitter','resizable,height=500,width=550,top=' + Math.max(Math.round(window.screen.height / 2 - 250),0) + ',left=' + Math.round(window.screen.width / 2 - 275)); return false;"><i></i><span class="twitter-label">Follow <b>@jroper</b></span></a></div>

footer: |
  Copyright James Roper.  <a rel="license" href="http://creativecommons.org/licenses/by-nc/2.5/au/">Some rights reserved</a>.

timezone: Australia/Canberra

assetsExpiry: 365 days
