title: all that jazz
subTitle: "james' blog about scala and all that jazz"
author: James Roper

theme: themes.Theme$

disqus_shortname: jazzyidau

description: |
  <img style="float: right; margin: 5px;" src="images/james.jpg"/>
  Hi! My name is James Roper, and I am a software developer with a particular interest in open source
  development and trying new things. I program in Scala, Java, PHP, Python and Javascript, and I work
  for <a href="http://typesafe.com">Typesafe</a> as a developer on
  <a href="http://playframework.com">Play framework</a>. I also have a full life outside the world of IT,
  am a passionate Christian, enjoy playing a variety of musical instruments and sports, and currently I
  live in Sydney.
  <br/>
  <br/>
  <a href="https://twitter.com/jroper" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @@jroper</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

footer: |
  <a rel="license" href="http://creativecommons.org/licenses/by-nc/2.5/au/"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/2.5/au/88x15.png" /></a>
  <br />
  Copyright James Roper.  This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/2.5/au/">Creative Commons Attribution-NonCommercial 2.5 Australia License</a>
