apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: codefresh-bot
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["update", "patch"]
  resourceNames: ["erqx"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: codefresh-bot
rules:
- apiGroups: [""]
  resources: ["namespaces", "nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: codefresh-bot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: codefresh-bot
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: codefresh-bot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: codefresh-bot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: codefresh-bot
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: codefresh-bot
  namespace: default
