apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: erqx-cert
spec:
  secretName: erqx-cert
  dnsNames:
  - jazzy.id.au
  - www.jazzy.id.au
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
