apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: erqx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  rules:
  - host: jazzy.id.au
    http:
      paths:
      - path: /
        backend:
          serviceName: erqx
          servicePort: 80
  tls:
  - secretName: erqx-cert
    hosts:
    - jazzy.id.au
    - www.jazzy.id.au

