apiVersion: apps/v1
kind: Deployment
metadata:
  name: erqx
  labels:
    app: erqx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erqx
  template:
    metadata:
      labels:
        app: erqx
    spec:
      containers:
      - name: erqx
        image: jamesroper/website:45af410
        args: ["-J-Xmx256m", "-J-Xms256m"]
        ports:
        - containerPort: 9000
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: erqx
              key: secret-key
        - name: FETCH_KEY
          valueFrom:
            secretKeyRef:
              name: erqx
              key: fetch-key

